namespace Compiler
{
    public enum TokenType
    {
        #pragma warning disable SA1602 // EnumerationItemsMustBeDocumented
        EOF,
        PLUS,
        MINUS,
        SLASH,
        ASTERISK,
        EQEQ,
        EQ,
        IDENT,
        IF,
        NUMBER,
        HEXNUMBER,
        BINNUMBER,
        SEMICOLON,
        BANG,
        TILDE,
        AND,
        GT,
        PERCENT,
        QUOTE,
        PIPE,
        QUESTION,
        CARET,
        LT,
        LPAREN,
        RPAREN,
        OPEN_ARROW,
        CLOSE_ARROW,
        NOTEQ,
        GTEQ,
        LTEQ,
        ANDAND,
        OROR,
        BIN_NUMBER,
        HEX_NUMBER,
        OCT_NUMBER,
        COLON,
        PRINT,
#pragma warning restore SA1602 // EnumerationItemsMustBeDocumented
    }
}
